Delivery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

from . import settings


urlpatterns = [
	path('admin/', admin.site.urls),
	path('', include('sukiya.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sukiya/urls.py
from django.urls import path
from . import views

app_name = 'sukiya'
urlpatterns = [
	path('', views.CategoryListView.as_view(), name='index'),
	path('item/<int:pk>', views.ItemListView.as_view(), name='item_list'),
	path('menu/<int:pk>', views.MenuListView.as_view(), name='menu_list')
]

user/urls.py
from django.conf.urls import url
from django.urls import path, include
from django.contrib import admin
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
app_name = "user"
urlpatterns = [
	# path('', views.Index.as_view(), name='index'),
	path('', indexView.as_view(), name='index'),
	path('mypage/<int:pk>', views.MyPage.as_view(), name='myp'),
	path('join/<int:uid>', views.group_join, name="group_join"),
	path('reject/<int:uid>', views.group_Reject, name="group_Reject"),
	path('remove/<int:uid>', views.group_remove, name="group_remove"),
]

sukiya/models.py
from django.db import models
from django.utils import timezone

from user.models import User


class Category(models.Model):
	name = models.CharField(
		verbose_name='カテゴリー名',
		max_length=50,
		null=True, blank=True,
	)

	memo = models.TextField(
		verbose_name='メモ',
		null=True, blank=True,
	)

	img = models.ImageField(
		upload_to='images/',
		null=True,
		blank=True
	)

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = 'カテゴリー'
		verbose_name_plural = 'カテゴリー'


class Item(models.Model):
	name = models.CharField(
		verbose_name='品名',
		max_length=100,
		null=True,
		blank=True
	)

	category = models.ForeignKey(
		Category,
		on_delete=models.CASCADE,
	)

	new = models.BooleanField(
		verbose_name='新商品',
		default=False
	)

	limited = models.BooleanField(
		verbose_name='期間限定',
		default=False
	)

	recommend = models.BooleanField(
		verbose_name='おすすめ',
		default=False
	)

	img = models.ImageField(
		upload_to='images/',
		null=True,
		blank=True
	)

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = '品名'
		verbose_name_plural = '品名'


class Menu(models.Model):
	size_choice = (
		("1", "ミニ"),
		("2", "並盛"),
		("3", "中盛"),
		("4", "大盛"),
		("5", "特盛"),
		("6", "メガ"),
		("7", "キング"),
	)

	item = models.ForeignKey(
		Item,
		on_delete=models.CASCADE,
		verbose_name='商品名'
	)

	size = models.CharField(
		choices=size_choice,
		max_length=10,
		null=True,
		blank=True
	)

	tax_price = models.PositiveIntegerField(
		verbose_name='税込価格',
		null=True,
		blank=True,
	)

	price = models.PositiveIntegerField(
		verbose_name='税抜価格',
		null=True,
		blank=True,
	)

	tax = models.PositiveSmallIntegerField(
		verbose_name='消費税',
		null=True,
		blank=True,
	)

	calorie = models.PositiveIntegerField(
		verbose_name='カロリー'
	)

	def __str__(self):
		return f'{self.item.name} ({self.get_size_display()})'

	def save(self, *args, **kwargs):
		tax_rate = 10
		tax = int(self.tax_price) * tax_rate / 110
		price = int(self.tax_price) / 1.1
		self.tax = tax
		self.price = price
		super(Menu, self).save(*args, **kwargs)

	class Meta:
		verbose_name = 'メニュー'
		verbose_name_plural = 'メニュー'


class SetMenu(models.Model):
	name = models.CharField(
		verbose_name='セットメニュー名',
		max_length=100
	)

	price = models.PositiveIntegerField(
		verbose_name='税込価格',
		null=True,
		blank=True,
	)

	img = models.ImageField(
		upload_to='images/',
		null=True,
		blank=True
	)

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = 'セットメニュー'
		verbose_name_plural = 'セットメニュー'


class OrderItem(models.Model):

	menu = models.ForeignKey(
		Menu,
		on_delete=models.CASCADE,
		verbose_name='メニュー'
	)

	set_menu = models.ForeignKey(
		SetMenu,
		on_delete=models.CASCADE,
		verbose_name='セット',
		null=True,
		blank=True
	)

	quantity = models.PositiveSmallIntegerField(
		verbose_name='数量',
		default=1
	)

	tax_rate = models.PositiveSmallIntegerField(
		verbose_name='税率',
		null=True,
		blank=True
	)

	price = models.PositiveIntegerField(
		verbose_name='金額',
		null=True,
		blank=True
	)

	takeout = models.BooleanField(
		verbose_name='持ち帰り',
		default=False
	)

	def save(self, *args, **kwargs):
		if self.takeout:
			self.tax_rate = 8
			tax = 8 / 100
			price = round(self.menu.price * tax)
			item_price = self.menu.price + price + self.set_menu.price
		else:
			self.tax_rate = 10
			item_price = self.menu.tax_price + self.set_menu.price
		self.price = item_price * self.quantity
		super(OrderItem, self).save(*args, **kwargs)

	def __str__(self):
		return self.menu.item.name

	class Meta:
		verbose_name = '注文商品'
		verbose_name_plural = '注文商品'


class Order(models.Model):
	table = models.PositiveSmallIntegerField(
		verbose_name='卓番',
	)

	number = models.PositiveIntegerField(
		verbose_name="伝票番号",
	)

	date = models.DateTimeField(
		verbose_name="来店時間",
		default=timezone.now,
	)

	order_item = models.ManyToManyField(
		OrderItem,
		verbose_name='注文商品'
	)

	total_price = models.PositiveIntegerField(
		verbose_name='合計金額'
	)

	ordered = models.BooleanField(
		verbose_name='注文済み',
		default=False
	)

	def __str__(self):
		return '%s %s' % (self.table_no, self.order_code)

	class Meta:
		verbose_name = '注文内容'
		verbose_name_plural = '注文内容'


class Invoice(models.Model):
	contact_user = models.ForeignKey(
		User,
		on_delete=models.CASCADE,
		verbose_name='担当者'
	)

	order = models.ForeignKey(
		Order,
		on_delete=models.CASCADE,
		verbose_name='注文内容'
	)

	leaved_date = models.DateTimeField(
		verbose_name='退店時間',
		null=True,
		blank=True
	)

	def __str__(self):
		return self.contact_user

sukiya/views.py
from django.views.generic import ListView, DetailView, TemplateView
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy

from .models import Category, Item, Menu, SetMenu, OrderItem, Order, Invoice


class CategoryListView(ListView):
	model = Category
	template_name = 'sukiya/category_list.html'


class ItemListView(ListView):
	model = Item
	template_name = 'sukiya/Item_list.html'

	def get_queryset(self):
		obj = Item.objects.filter(category_id=self.kwargs['pk'])
		qs = obj.order_by('pk')
		return qs

	def get_context_data(self, *, object_list=None, **kwargs):
		context = super().get_context_data(**kwargs)
		return get_context(context)


class MenuListView(ListView):
	model = Menu
	template_name = 'sukiya/menu_list.html'

	def get_queryset(self):
		obj = Menu.objects.filter(item_id=self.kwargs['pk']).order_by('calorie')
		return obj

	def get_context_data(self, *, object_list=None, **kwargs):
		context = super().get_context_data(**kwargs)
		item = Item.objects.get(pk=self.kwargs['pk'])
		context['item'] = item
		return get_context(context)


def get_context(context):
	set_menu_list = SetMenu.objects.all()
	size_choices = Menu.size_choice
	size_dict = {}
	for size in size_choices:
		size_dict[size[0]] = size[1]
	context['size_dict'] = size_dict
	context['set_menu_list'] = set_menu_list
	return context

templates/sukiya/category_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="row">
        <div class="col-9 order-menu">
            <div class="row row-cols-1 row-cols-md-3">
                {% for category in category_list %}
                    <div class="col">
                        <div class="card" id="category{{ category.pk }}">
                            <img src="{{ category.img.url }}" class="card-img" alt="{{ category.name }}">
                            <div class="card-img-overlay">
                                <h5 class="card-title" style="text-align: center;">{{ category.name }}</h5>
                            </div>
                        </div>
                    </div>
                {% empty %}
                    none
                {% endfor %}
            </div>
        </div>
        <div class="col-3">
            {% include 'side_cart.html' %}
        </div>
    </div>

{% endblock %}

{% block javascript %}

    <script type="text/javascript">
        {% for category in category_list %}
            $('#category{{ category.pk }}').click(function() {
                window.location.href = "{% url 'sukiya:item_list' category.pk %}";
            });
        {% endfor %}
    </script>

{% endblock javascript %}

templates/sukiya/item_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="modal fade" id="modal" tabindex="-1" aria-labelledby="modal" aria-hidden="true">
        <div class="modal-dialog modal-xl">
            <div class="modal-content"></div>
        </div>
    </div>

    <div class="row">
        <div class="col-9 order-menu">
            <div class="row row-cols-1 row-cols-md-3">
                {% for item in item_list %}
                    <div class="col">
                        <div class="card" id="item{{ item.pk }}" data-toggle="modal">
                            <img src="{{ item.img.url }}" class="card-img" alt="{{ item.name }}">
                            <div class="card-img-overlay">
                                <p>{{ item.name }}</p>
                            </div>
                        </div>
                    </div>
                {% empty %}
                    none
                {% endfor %}
            </div>
        </div>
        <div class="col-3">
            {% include 'side_cart.html' %}
        </div>
    </div>


{% endblock %}

{% block javascript %}

    <script type="text/javascript">

    $(function() {
        {% for item in item_list %}
            $("#item{{ item.pk }}").each(function() {
                $(this).modalForm({formURL: "{% url 'sukiya:menu_list' item.pk %}"});
            });
        {% endfor %}
        $('#modal').on('show.bs.modal', function() {
            let sizeText = $(".size-text")
            {% for key, size in size_dict.items %}
                $("#size{{ key }}").click(function() {
                    if ($(".is-active").length){
                        let replaceText = sizeText.text().replace("{{ size }}", "");
                        sizeText.text(replaceText);
                        $(".size-card").removeClass("is-active");
                        $(this).addClass("is-active");
                        $(sizeText).append("{{ size }}");
                    } else {
                        $(this).addClass("is-active");
                        $(sizeText).append();
                    }

                });
            {% endfor %}
            let findIsActive = $("#nonSet").find(".is-active");
            {% for set_menu in set_menu_list %}
                $(".setmenu-card").click(function() {
                    if ($(".is-active").length){
                        if (findIsActive) {
                            $("#nonSet").removeClass(("is-active"));
                        }
                        $("#set{{ set_menu.pk }}").removeClass("is-active");
                        $(this).addClass("is-active");
                    } else {
                        $(this).addClass("is-active");
                    }
                });
            {% endfor %}
            let orderItem = $(".order-item").find("p")
            {% for menu in menu_list %}
                $orderItem

            {% endfor %}
        });

    });

    </script>

{% endblock javascript %}

templates/sukiya/menu_list.html
<div class="modal-body">
    <div class="row">
        <div class="col-9">
            <div class="row select-menu">
                <h5 class="menu-title">選択メニュー</h5>
                <div class="col-6 size-select">
                    <h5 class="size-title">サイズ変更</h5>
                    <div class="row row-cols-1 row-cols-md-2">

                        {% for menu in menu_list %}
                            <div class="col">
                                <div class="card text-center mb-3 size-card" id="size{{ menu.size }}">
                                    <div class="card-body">
                                        <p class="card-text">{{ menu.get_size_display }}</p>
                                    </div>
                                </div>
                            </div>
                        {% empty %}
                            とうろくしてください
                        {% endfor %}
                    </div>
                </div>
                <div class="col-6 set-select">
                    <h5 class="set-title">お得なセットメニュー</h5>
                    {% for set_menu in set_menu_list %}
                    <div class="row">
                        <div class="col">
                            <div class="card mb-2 setmenu-card" id="set{{ set_menu.pk }}">
                                <div class="card-body">
                                    <div class="col-12">
                                        <p class="card-text">{{ set_menu.name }} {{ set_menu.price }}円</p>
                                        <img src="{{ set_menu.img.url }}" alt="{{ set_menu.name }}">
                                    </div>
                                </div>
                            </div>
                            {% if forloop.last %}
                                <div class="card mb-2 setmenu-card" id="nonSet">
                                    <div class="card-body">
                                        <div class="col-12">
                                            <p class="card-text">セットメニューなし</p>
                                        </div>
                                    </div>
                                </div>
                            {% else %}
                            {% endif %}
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="col-3 order-item">
            <h5 class="menu-title">注文商品</h5>
            <div class="row select-item">
                <p class="item-name">{{ item.name }}</p>
                <p class="size-text"></p>
                <img src="{{ item.img.url }}" alt="{{ item.name }}" class="item-image">
            </div>
            <div class="row select-price">
                <i class="fas fa-minus-square"></i>
                <p class="item-price">price</p>
                <i class="fas fa-plus-square"></i>
            </div>
            <div class="row">
                <p>小計金額</p>
                <div class="d-grid gap-2">
                    <button type="button" class="btn btn-block btn-info menu-cancel" data-bs-dismiss="modal">キャンセル</button>
                    <button type="button" class="btn byn-block btn-danger menu-order">注文リストに追加</button>
                </div>
            </div>
        </div>
    </div>
</div>